name: lorescanner
description: "A scanner application for the Lorcana TCG by Ravensburger"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  opencv_dart: ^1.4.1
  camera: ^0.11.1

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
