name: lorescanner
description: "A scanner application for the Lorcana TCG by Ravensburger"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.1
  path: ^1.9.1
  path_provider: ^2.1.5
  persistent_bottom_nav_bar_v2: ^6.1.0
  google_mlkit_text_recognition: ^0.15.0
  dart_mappable: ^4.5.0
  url_launcher: ^6.3.1
  sqflite: ^2.4.2
  provider: ^6.1.5
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  dart_mappable_builder: ^4.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png